### PR TITLE
Added functionality

### PR DESCRIPTION
**Pull request by LunarKitsune**
Small list of changes requested for the pull request:
1: Added conversion function for converting Celsius to Fahrenheit called convertToF()
2: Due to number one: also added an optional bool parameter to readTemperature()
      -This will let a programmer choose if the temperature output is Celsius or Fahrenheit
3: Fixed readHumidity function so it returns 0 if below 0 (this will be tested once I get the product in. 
[Adafruit_Si7021Changes.zip](https://github.com/adafruit/Adafruit_Si7021/files/5357303/Adafruit_Si7021Changes.zip)

### CODE REVIEW

**Comment by ladyada** [comment]
hmm can you try making a fresh PR based off 'master' branch? the files all changed and its hard to tell what ya added :)

**Comment by LunarKitsune** [comment]
Sure. Ill be able to later. I tried adding the main header file and the main cpp file and it wasnt letting me earlier.

**Comment by LunarKitsune** [comment]
My apologies ladyada. It won't let me create a new PR request as the button is dulled out and non functional when I have master selected. It was the reason I selected "actionci from master" when I submitted it.

**Comment by ladyada** [comment]
your PR should be from _your_ fork master to this repo.

**Comment by LunarKitsune** [comment]
Thank you for the patience. Im decent at coding, but not decent enough at github and it clicked with me after you said that. :) New pull request should be put in now. This pull request will be closed.

**Pull request closed without merging**
