### PR TITLE
Add CRC8, add SHT2x support

### PR DESCRIPTION
**Pull request by stickbreaker**

### CODE REVIEW

**Comment by stickbreaker** [comment]
This is output from an ESP32 with a SHT25 (controlEverything.com SHT25 Rev.D)
>Si7021 test!
Found model SHT25  Rev(1) Serial #4146979B1510080
Humidity:    22.99%	Temperature: 26.11
Humidity:    23.11%	Temperature: 26.11
Humidity:    23.19%	Temperature: 26.11
Humidity:    23.19%	Temperature: 26.11

This code is untested with Si70nn devices.  I do not have any available for testing.

**Comment by stickbreaker** [comment]
Corrected output
>Si7021 test!
Found model SHT25  Rev(1) Serial #4146979B01510080
Humidity:    22.16%	Temperature: 26.63
Humidity:    22.16%	Temperature: 26.64
Humidity:    22.20%	Temperature: 26.65
Humidity:    22.44%	Temperature: 26.65

**Comment by ladyada** [comment]
we wont be merging until someone tests with Si7021
thanx!

**Comment by d235j** [comment]
@stickbreaker it looks like the implementation of the calcCrc() method is missing? I get a link error; this should not link even for SHT2x as-is.

**Comment by stickbreaker** [comment]
@d235j Yea, copy paste error when I manually made a patch branch. That's what I get for assumptions.  It should work now. but, I'm not in a position to test it.  Please try it.

Chuck.

**Comment by d235j** [comment]
@stickbreaker @ladyada Seems to work correctly with Si7021 now.
I don't have an SHT2x — @stickbreaker any chance you could test it with that sensor?

**Comment by stickbreaker** [comment]
@d235j  I have tested it , and it is working with a SHT25, I don't have SHT20 or SHT21.  The datasheet says they are interchangeable, except they have lower accuracy.  So.  I don't expect any any problems with them.

Chuck.

**Comment by ladyada** [comment]
hiya would this be a better addition to 
https://github.com/adafruit/Adafruit_SHT31
? maybe the same family, has more similarities

**Comment by caternuson** [comment]
Agree that this repo does not seem like a good place for hosting SHT2x support. The SHT2x is made by Sensirion. The Si7021 is made by Silicon Labs.

Closing for now. If the CRC check is something still desired, can resubmit a new PR based on latest library updates.

**Pull request closed without merging**
