### PR TITLE
Re-Done Pull Request for small list changes

### PR DESCRIPTION
**Pull request by LunarKitsune**
1: Added function for temperature conversion
2: Added bool parameter to readtemperature() for temperature conversion
3: Fixed readHumidity() return statement so there is no negative humidity read.

### CODE REVIEW

**Comment by LunarKitsune** [comment]
Clang seems to not like my code somehow. Where I went wrong was parameter declaration initially in Adafruit_Si7021.h where I had things backwards in doing optional parameter in definition instead of declaration. Need to see what clang doesn't like for fix.

**Comment by LunarKitsune** [comment]
My temperature conversion method has been confirmed to work, and humidity is working well. No errors in the reading with my personal code I am using. Clang still doesn't seem to accept the code.

**Comment by ladyada** [comment]
yeha your PR made a ton of whitespace changes. do you have any way to run clang-format -i on the files?

**Comment by caternuson** [comment]
Closing. Looks like this has stalled. It never passed CI and now has merge conflicts.

**Pull request closed without merging**
